import { cn } from '@/lib/utils';
import { geistMono, geistSans } from '@/ui/font';
import '@/ui/globals.css';
import type { Metadata } from 'next';
import { Suspense } from 'react';
import { Provider } from './provider';
import { Header } from './modules/header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        `${geistSans.variable} ${geistMono.variable} antialiased`,
        'h-full'
      )}
    >
      <body>
        <Suspense fallback={null}>
          <Provider header={<Header />}>{children}</Provider>
        </Suspense>
      </body>
    </html>
  );
}
